# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: rilin.me
author: Роман Ильин
email: me@rilin.me
description: >-
  Персональный сайт.
baseurl: /
url: https://rilin.me

plugins:
  - jekyll-feed
#  - jekyll-paginate

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed

#paginate: 1
